### ISSUE TITLE
Not compatible with OpenJDK 11.

### ISSUE THREAD

**Issue by Eric-Tobias** [wvengen/proguard-maven-plugin#106]
Building projects using the OpenJDK 11 fails.

**Comment by lasselindqvist** [comment]
This would need an example pom.xml or a project and a stacktrace.

**Comment by Eric-Tobias** [comment]
Thank you for the quick reply. It seems the rt.jar cannot be located in the OpenJDK as suggested by the following partial stak trace:

> [proguard] java.io.IOException: Can't read [C:\Program Files\AdoptOpenJDK\jdk-11.0.4.11-hotspot\lib\rt.jar] (No such file or directory)
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:188)
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:158)
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:136)
 [proguard] 	at proguard.InputReader.execute(InputReader.java:88)
 [proguard] 	at proguard.ProGuard.readInput(ProGuard.java:218)
 [proguard] 	at proguard.ProGuard.execute(ProGuard.java:82)
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:538)
 [proguard] Caused by: java.io.IOException: No such file or directory
 [proguard] 	at proguard.io.DirectoryPump.pumpDataEntries(DirectoryPump.java:50)
 [proguard] 	at proguard.InputReader.readInput(InputReader.java:184)
 [proguard] 	... 6 more
BUILD FAILURE
Total time: 2.025 s
Finished at: 2020-01-26T12:12:41+01:00
Final Memory: 16M/67M
Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.0.14:proguard (default) on project AirliftRescue: Obfuscation failed (result=1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.0.14:proguard (default) on project AirliftRescue: Obfuscation failed (result=1)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Obfuscation failed (result=1)
	at com.github.wvengen.maven.proguard.ProGuardMojo.proguardMain(ProGuardMojo.java:814)
	at com.github.wvengen.maven.proguard.ProGuardMojo.execute(ProGuardMojo.java:617)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 20 more

The only changes I made for this old project was updating from Java 9 to the OpenJDK in version 11.

**Comment by lasselindqvist** [comment]
Java 11 no longer contains rt.jar. It is likely you define it in your libraryjars still and that is what causes the failure.
For Java 11 you would want to add
`<java.home>/jmods/java.base.jmod`
there.

**Comment by Eric-Tobias** [comment]
You are right, the library JARs I was referencing were rt and jsse. Any idea by what isse got replaced?

**Comment by patrickfav** [comment]
Just as input, my tests with JDK 11 are positive, so this might be a setup issue on your end @Eric-Tobias

**Comment by Eric-Tobias** [comment]
> 
> 
> Just as input, my tests with JDK 11 are positive, so this might be a setup issue on your end @Eric-Tobias

Did you test with Oracle's JDK or the OpenJDK?

**Comment by patrickfav** [comment]
OpenJdk11 (who uses Oracle JDK anymore 😆). This project: https://github.com/patrickfav/bcrypt and this build: https://travis-ci.org/github/patrickfav/bcrypt/builds/677812659

**Comment by ravpod** [comment]
I have similar problem after update to OpenJDK11. I defined plugin in pom like below 
`<plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
                <version>2.2.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>proguard</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <options>
                        <option>-keepdirectories</option>
                        <option>-keepattributes
                            Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod
                        </option>
                        <option>-keepclassmembers enum * {public static **[] values(); public static **
                            valueOf(java.lang.String);}
                        </option>
                        <option>-keepclassmembers class * implements java.io.Serializable { static final long
                            serialVersionUID; private static final java.io.ObjectStreamField[] serialPersistentFields;
                            private void writeObject(java.io.ObjectOutputStream); private void
                            readObject(java.io.ObjectInputStream); java.lang.Object writeReplace(); java.lang.Object
                            readResolve();}
                        </option>

                        <option>-allowaccessmodification</option>

                        <option>-keep public class * { public protected *;}</option>

                        <option>-renamesourcefileattribute SourceFile</option>
                    </options>
                    <libs>
                        <lib>${java.home}/lib/jsse.jar</lib>
                        <lib>${java.home}/lib/jce.jar</lib>
                        <lib>${java.home}/lib/ext/sunjce_provider.jar</lib>
                    </libs>
                </configuration>
            </plugin>`

**Comment by lasselindqvist** [comment]
@ravpod you would have to post the actual error message from Proguard. Your stacktrace doesn't show it.

**Comment by ravpod** [comment]
> @ravpod you would have to post the actual error message from Proguard. Your stacktrace doesn't show it.

It's the only stacktraction I can get. I used the -X flag when compiling my project.

**Comment by ravpod** [comment]
@lasselindqvist in my case it was problem with libs I changed path to jmod directory and now works.

**Comment by maurizio-lattuada** [comment]
@ravpod for the records, this helps also with JDK17.

For ease of reading:
```xml
<libs>
    <lib>${java.home}/jmods/java.base.jmod</lib>
    <lib>${java.home}/jmods/java.datatransfer.jmod</lib>
    <lib>${java.home}/jmods/java.prefs.jmod</lib>
    <lib>${java.home}/jmods/java.xml.jmod</lib>
    <lib>${java.home}/jmods/java.desktop.jmod</lib>
</libs>
```

**Comment by kaosko** [comment]
If you are not interested in tracking which module a certain core Java class comes from, this will also work on all JDKs, 9 and above:
<libs>
    <lib> ${java.home}/jmods/</lib>
</libs>

**Comment by lasselindqvist** [comment]
Closing as this should be resolved with the examples in comments.
