### ISSUE TITLE
java.lang.VerifyError: Expecting a stackmap frame at branch target 10

### ISSUE THREAD

**Issue by ypkkhatri** [wvengen/proguard-maven-plugin#139]
After successfully obfuscation unable to run jar, below is the error:
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.VerifyError: Expecting a stackmap frame at branch target 10
Exception Details:
  Location:
    com/my/app/Start.a([Ljava/lang/String;)V @3: ifne
  Reason:
    Expected stackmap frame at this location.
  Bytecode:
    0x0000000: b800 469a 0007 04b8 005c bb00 1e59 2ab7
    0x0000010: 0048 4c2b b600 4a2b 1218 b600 494d 2b12
    0x0000020: 17b6 0049 4e2b 1219 b600 493a 042c c600
    0x0000030: 232c 1201 b600 579a 001a 2dc6 0016 1904
    0x0000040: c600 11bb 0031 592c 2d19 04b7 005e b800
    0x0000050: 5f2b 120d b600 49b8 003f 2b12 0cb6 0049
    0x0000060: b800 402b 1209 b600 49b8 0041 2b12 0eb6
    0x0000070: 0049 b800 422b 120a b600 49b8 0043 2b12
    0x0000080: 0fb6 0049 b800 442b 120b b600 49b8 0045
    0x0000090: 2b12 11b6 0049 3a05 013a 0619 05c6 004f
    0x00000a0: 1905 2bb8 003c 3a06 1906 c600 0e19 06b6
    0x00000b0: 003d 9900 06a7 003f 1906 c600 1819 06b6
    0x00000c0: 003d 9a00 1019 06b6 003e 2bb8 003b 57a7
    0x00000d0: 0025 b200 3a12 07b9 0065 0200 0112 0712
    0x00000e0: 0303 b800 6003 b800 5ca7 000b 1205 2bb8
    0x00000f0: 003b 3a06 1906 c6ff a519 06b6 003d 99ff
    0x0000100: 9d2b 1216 b600 493a 0719 07b8 0053 b600
    0x0000110: 543a 0819 08c1 0033 9900 0e19 08c0 0033
    0x0000120: b800 62a7 0060 1908 c100 3799 0058 bb00
    0x0000130: 2c59 b700 5912 08b6 005a 1907 1215 b600
    0x0000140: 5804 3212 06b6 0058 0332 b600 5a12 04b6
    0x0000150: 005a b600 5b3a 0912 143a 0abb 002c 59b7
    0x0000160: 0059 190a b600 5a19 09b6 005a b600 5b3a
    0x0000170: 0b19 0bb8 0053 b600 54c0 0033 3a0c 190c
    0x0000180: b800 62a7 0014 3a07 b200 3a12 0219 07b6
    0x0000190: 0055 b900 6603 002b 1212 b600 493a 0719
    0x00001a0: 07b8 0051 2b12 13b6 0049 3a08 1210 1908
    0x00001b0: b600 5799 0029 bb00 2059 b700 4d3a 0919
    0x00001c0: 092b 1906 b600 4ea7 0012 3a0a b200 3a19
    0x00001d0: 0ab6 0052 b900 6502 00a7 0026 bb00 1f59
    0x00001e0: b700 4b3a 0919 092b 1906 b600 4ca7 0012
    0x00001f0: 3a0a b200 3a19 0ab6 0055 b900 6502 00b1
    0x0000200:
  Exception Handler Table:
    bci [257, 387] => handler: 390
    bci [257, 387] => handler: 390
    bci [257, 387] => handler: 390
    bci [257, 387] => handler: 390
    bci [447, 455] => handler: 458
    bci [485, 493] => handler: 496

        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

pom.xml plugin:
```
          <plugin>
                <groupId>com.github.wvengen</groupId>
                <artifactId>proguard-maven-plugin</artifactId>
                <version>2.3.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>proguard</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <obfuscate>true</obfuscate>
                    <injar>${project.build.finalName}.jar</injar>
                    <outjar>${project.build.finalName}-obfs.jar</outjar>
                    <includeDependencyInjar>false</includeDependencyInjar>
                    <includeDependency>true</includeDependency>
                    <options>
                        <option>-dontnote</option>
                        <option>-dontshrink</option>
                        <option>-dontoptimize</option>
                        <option>-dontpreverify</option>
                        <option>-dontskipnonpubliclibraryclasses</option>
                        <option>-dontskipnonpubliclibraryclassmembers</option>
                        <option>-allowaccessmodification</option>
                        <option>-keep public class com.my.app.Start{public static void main(java.lang.String[]);}</option>
                    </options>
                    <libs>
                        <lib>${java.home}/lib/rt.jar</lib>
                        <lib>${java.home}/lib/jce.jar</lib>
                        <lib>${java.home}/lib/ext/jfxrt.jar</lib>
                    </libs>
                    <archive>
                        <manifest>
                            <mainClass>Start</mainClass>
                            <packageName>com.my.app</packageName>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
```

**Comment by ypkkhatri** [comment]
I have tried latest versions of this plugin but still same issue.

**Comment by lasselindqvist** [comment]
Seems like an issue with Proguard core itself. You need to report this there.
https://github.com/Guardsquare/proguard/issues
