### ISSUE TITLE
ITs fail on Java 11

### ISSUE THREAD

**Issue by lasselindqvist** [wvengen/proguard-maven-plugin#161]
ITs fail on Java 11:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.369 s
[INFO] Finished at: 2021-09-26T19:52:55+03:00
[INFO] ------------------------------------------------------------------------
[WARNING] The requested profile "integration-test" could not be activated because it does not exist.
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project simple: Compilation failure: Compilation failure: 
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]

**Comment by lasselindqvist** [comment]
With Java 11 fails to:
```
 [proguard] Initializing...
 [proguard] Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/logging/log4j/LogManager
 [proguard] 	at proguard.classfile.editor.CodeAttributeEditor.<clinit>(CodeAttributeEditor.java:113)
 [proguard] 	at proguard.classfile.util.DynamicMemberReferenceInitializer.<init>(DynamicMemberReferenceInitializer.java:87)
 [proguard] 	at proguard.Initializer.execute(Initializer.java:246)
 [proguard] 	at proguard.ProGuard.initialize(ProGuard.java:327)
 [proguard] 	at proguard.ProGuard.execute(ProGuard.java:132)
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:717)
 [proguard] Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.LogManager
 [proguard] 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
 [proguard] 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
 [proguard] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
 [proguard] 	... 6 more
```
We need to start also adding some other JARs to classpath, Now we only add the ones from getProguardJars method. This is why also Kotlin obfuscation might have failed even previously.
```
		for (File p : proguardJars)
			java.createClasspath().createPathElement().setLocation(p);
```

**Comment by lasselindqvist** [comment]
See also https://github.com/wvengen/proguard-maven-plugin/issues/122
