### ISSUE TITLE
NullPointerException for wrong configuration

### ISSUE THREAD

**Issue by zalavaari** [wvengen/proguard-maven-plugin#21]
Hi!
I forgot to define some properties in my pom.xml, so the proguard config contained some unresolved variables. To be explicit:
<option>-keepattributes ${proguard.keepattributes}</option>
My reward was the following NPE:

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.wvengen:pr
oguard-maven-plugin:2.0.7:proguard (default) on project ammo-limited: Execution default of goal com.
github.wvengen:proguard-maven-plugin:2.0.7:proguard failed.
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu
ilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBu
ilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter
.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.github.wv
engen:proguard-maven-plugin:2.0.7:proguard failed.
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.j
ava:110)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: java.lang.NullPointerException
        at com.github.wvengen.maven.proguard.ProGuardMojo.proguardMain(ProGuardMojo.java:640)
        at com.github.wvengen.maven.proguard.ProGuardMojo.execute(ProGuardMojo.java:497)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.j
ava:101)
        ... 20 more

**Comment by FibreFoX** [comment]
This might no longer be valid, because the code behind has changed.

Buggy code [from 2.0.7](https://github.com/wvengen/proguard-maven-plugin/blob/ea649c5e41d7ff46ac1c7f2a2ed3d6d1baae417b/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L640) until [current availabe version 2.0.11](https://github.com/wvengen/proguard-maven-plugin/blob/fe687221c4eab539932fec8ff2f6e39226a4679d/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L670):
```java
for (Iterator i = argsList.iterator(); i.hasNext();) {
    java.createArg().setValue(i.next().toString());
}
```

[Current implementation](https://github.com/wvengen/proguard-maven-plugin/blob/4d30721e4e09b2c826da62104ba433059216a3fe/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L761) (got changed while adding IT-projects):
```java
for (String arg : argsList) {
    java.createArg().setValue(arg);
}
```

As it isn't possible to have `toString()` be called on `null`-items, this issue should AFAIK be closed (and it is over a year old).

**Comment by wvengen** [comment]
Thanks for looking into this @FibreFoX! I think you're right. (Strange `i.next()` was previously called _within_ the loop.)
