### ISSUE TITLE
The input is empty. You have to specify one or more '-injars' options

### ISSUE THREAD

**Issue by takeAction** [wvengen/proguard-maven-plugin#348]
spring boot 2.x, jdk 1.8, maven 3.5, proguard 7.2.2 and  proguard-maven-plugin 2.6.0.
my configuration as follows:
```
<build>
		...
		<plugins>
						
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-war-plugin</artifactId>				
				<configuration>
					<outputDirectory>${war.output.dictionary}</outputDirectory>
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<version>2.6.0</version>
				<executions>
					<execution>
						<phase>compile</phase>
						<goals>
							<goal>proguard</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<proguardVersion>7.2.2</proguardVersion>
					<obfuscate>true</obfuscate>
					<proguardInclude>E:/proguard.cfg</proguardInclude>
					<libs>
						<lib>${java.home}/lib/rt.jar</lib>
					</libs>
					<injar>classes</injar>
					<outputDirectory>proguard</outputDirectory>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>com.guardsquare</groupId>
						<artifactId>proguard-base</artifactId>
						<version>7.2.2</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
		
		<resources>
			<resource>
				<directory>src/main/resources</directory>  
                <filtering>true</filtering>
                <includes>
                	<include>**/*.properties</include>
                	<include>**/*.yml</include><!-- 也可以指定具体的文件 application-${env}.yml -->
                </includes>                
			</resource>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>false</filtering>
				<excludes>
					<exclude>**/*.properties</exclude>
					<exclude>**/*.yml</exclude>
				</excludes>
			</resource>
		</resources>
		
	</build>
```
my project is packaged as `war`.
I want to obfuscate the `war` or its classes, when I execute `mvn clean package` in `idea`, the error thrown:
```
[proguard] ProGuard, version 7.2.2
 [proguard] Unexpected error
 [proguard] java.io.IOException: The input is empty. You have to specify one or more '-injars' options.
 [proguard] 	at proguard.ConfigurationChecker.check(ConfigurationChecker.java:62) ~[proguard-base-7.2.2.jar:7.2.2]
 [proguard] 	at proguard.ProGuard.checkConfiguration(ProGuard.java:290) ~[proguard-base-7.2.2.jar:7.2.2]
 [proguard] 	at proguard.ProGuard.execute(ProGuard.java:99) ~[proguard-base-7.2.2.jar:7.2.2]
 [proguard] 	at proguard.ProGuard.main(ProGuard.java:623) [proguard-base-7.2.2.jar:7.2.2]
```
what's the problem? I have set `injar` as `classes` and `phase` of `execution` as `compile`.

**Comment by lasselindqvist** [comment]
Based on your code, your injar parameter points to a directory of class files, not a JAR file. Try changing that.

**Comment by takeAction** [comment]
@lasselindqvist but from `plugin.xml` of `proguard-maven-plugin`, it says the `injar` is about
```
Specifies the input jar name (or wars, ears, zips) of the application to be processed. You may specify a classes directory e. g. 'classes'. This way plugin will processed the classes instead of jar. You would need to bind the execution to phase 'compile' or 'process-classes' in this case.
```
does I misunderstand it?

**Comment by takeAction** [comment]
I added `outputDirectory` of `proguard-maven-plugin` in my case because I want to generate the obfuscated classes in the specified folder under `target` directory.

After I remove this parameter, this error gone, the obfuscated classes are in `classes` folder and the un-obfuscated classes are in `classes_proguard_base` folder.
Thanks @lasselindqvist !

**Comment by wongshini** [comment]
Hello.
This is the configuration:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.springboot</groupId>
	<artifactId>user</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>war</packaging>

	<name>user</name>
	<description>Spring Boot Microservice for User</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.4.2</version>
		<relativePath/>
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>21</java.version>
		<maven-jar-plugin.version>3.2.0</maven-jar-plugin.version>
	</properties>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>21</source>
					<target>21</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.22.2</version>
				<configuration>
					
				</configuration>
			</plugin>
			<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<version>2.7.0</version>
				<executions>
					<execution>
						<phase>prepare-package</phase>
						<phase>compile</phase>
						<goals>
							<goal>proguard</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<obfuscate>true</obfuscate>
					<shrink>false</shrink>
					<optimize>false</optimize>
					<verbose>true</verbose>
					<printconfiguration>true</printconfiguration>
					<configurationFile>${project.basedir}/proguard.pro</configurationFile>
					<injars>${project.build.directory}/${project.build.finalName}.war</injars>
					<outjars>${project.build.directory}/${project.build.finalName}-obf.jar</outjars>
				</configuration>
			</plugin>
		</plugins>
		<finalName>user</finalName>
	</build>
</project>

`

I am getting below error after mvn clean package.

[INFO] proguard jar: [C:\Users\P1349608\.m2\repository\com\guardsquare\proguard-base\7.7.0\proguard-base-7.7.0.jar, C:\Users\P1349608\.m2\repository\com\guardsquare\proguard-core\9.1.10\proguard-core-9.1.10.jar]
 [proguard] ProGuard, version 7.7.0
 [proguard] Unexpected error
 [proguard] java.io.IOException: The input is empty. You have to specify one or more '-injars' options.
 [proguard]     at proguard.ConfigurationVerifier.check(ConfigurationVerifier.java:62) ~[proguard-base-7.7.0.jar:7.7.0]
 [proguard]     at proguard.ProGuard.checkConfiguration(ProGuard.java:317) ~[proguard-base-7.7.0.jar:7.7.0]
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:111) ~[proguard-base-7.7.0.jar:7.7.0]
 [proguard]     at proguard.ProGuard.main(ProGuard.java:649) [proguard-base-7.7.0.jar:7.7.0]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  17.097 s
[INFO] Finished at: 2025-04-13T12:01:19+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.7.0:proguard (default) on project user: Obfuscation failed (result=1) -> [Help 1]

May i know why ProGuard couldn’t find any files to process for obfuscation? What's wrong with configuration? Thanks
