### ISSUE TITLE
NullPointerException at ProGuardMojo

### ISSUE THREAD

**Issue by MdSE** [wvengen/proguard-maven-plugin#41]
I'm configuring a existing [maven] project to use ProGuard and I'm no being able to find the cause of this error: 

```
Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.0.11:proguard (proguard) on project xxxx: Execution proguard of goal com.github.wvengen:proguard-maven-plugin:2.0.11:proguard failed. NullPointerException
...
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution proguard of goal com.github.wvengen:proguard-maven-plugin:2.0.11:proguard failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.lang.NullPointerException
	at com.github.wvengen.maven.proguard.ProGuardMojo.execute(ProGuardMojo.java:506)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)

```

I'm using:
proguard-maven-plugin:2.0.11
spring-boot-maven-plugin:1.2.8.RELEASE

I also tried to avoid this part of the code by adding:
includeDependency:false and includeDependencyInjar:false but the error still occurs

Does anyone has the same or related problem, or have any clue how to overcome this error?

Thanks in advance

**Comment by cmorty** [comment]
@MdSE Were you able to fix this?

**Comment by MdSE** [comment]
@cmorty Yes, i was. The solutions was related with bad configuration/understanding of maven plugin. You can find the correction here: http://stackoverflow.com/questions/35065609/nullpointerexception-proguard-spring-boot

**Comment by cmorty** [comment]
@MdSE OK, I'll close it. A patch to catch that null-pointer and say something like "Empty library - ignoring" - or whatever you think best - is still welcome.
