### ISSUE TITLE
 Obfuscation failed (result=1)

### ISSUE THREAD

**Issue by nchidipo** [wvengen/proguard-maven-plugin#45]
Hi,

while executing obfuscate for my java code, it's getting fail. 

As my log file is huge size, i am attaching only error info.

 [proguard] Note: duplicate definition of library class [java.lang.OutOfMemoryError]
 [proguard] Note: duplicate definition of library class [java.lang.VirtualMachineError]
 [proguard] Note: duplicate definition of library class [java.lang.ArrayStoreException]
 [proguard] Note: duplicate definition of library class [java.lang.ClassCastException]
 [proguard] Note: duplicate definition of library class [java.lang.LinkageError]
 [proguard] Note: duplicate definition of library class [java.lang.NoClassDefFoundError]
 [proguard] Note: duplicate definition of library class [java.lang.ClassNotFoundException]
 [proguard] Note: duplicate definition of library class [java.security.AccessControlContext]
 [proguard] Note: duplicate definition of library class [java.security.ProtectionDomain]
 [proguard] Note: duplicate definition of library class [java.lang.RuntimeException]
 [proguard] Note: duplicate definition of library class [java.lang.Exception]
 [proguard] Note: duplicate definition of library class [java.lang.ThreadDeath]
 [proguard] Note: duplicate definition of library class [java.lang.Error]
 [proguard] Note: duplicate definition of library class [java.lang.Throwable]
 [proguard] Note: duplicate definition of library class [java.lang.System]
 [proguard] Note: duplicate definition of library class [java.lang.ClassLoader]
 [proguard] Note: duplicate definition of library class [java.lang.Cloneable]
 [proguard] Note: duplicate definition of library class [java.lang.Class]
 [proguard] Note: duplicate definition of library class [java.lang.Comparable]
 [proguard] Note: duplicate definition of library class [java.io.Serializable]
 [proguard] Note: duplicate definition of library class [java.lang.String]
 [proguard] Note: duplicate definition of library class [java.lang.Object]
 [proguard] Note: there were 15844 duplicate class definitions.
 [proguard](http://proguard.sourceforge.net/manual/troubleshooting.html#duplicateclass)
 [proguard] Warning: there were 1632 classes in incorrectly named files.
 [proguard]          You should make sure all file names correspond to their class names.
 [proguard]          The directory hierarchies must correspond to the package hierarchies.
 [proguard](http://proguard.sourceforge.net/manual/troubleshooting.html#unexpectedclass)
 [proguard]          If you don't mind the mentioned classes not being written out,
 [proguard]          you could try your luck using the '-ignorewarnings' option.
 [proguard] java.io.IOException: Please correct the above warnings first.
 [proguard]     at proguard.InputReader.execute(InputReader.java:123)
 [proguard]     at proguard.ProGuard.readInput(ProGuard.java:218)
 [proguard]     at proguard.ProGuard.execute(ProGuard.java:82)
 [proguard]     at proguard.ProGuard.main(ProGuard.java:538)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 41.606s
[INFO] Finished at: Thu May 05 13:03:25 PDT 2016
[INFO] Final Memory: 38M/472M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.0.11:proguard (default) on project server-query-engine: Obfuscation failed (result=1) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.wvengen:proguard-maven-plugin:2.0.11:proguard (default) on project server-query-engine: Obfuscation failed (result=1)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:318)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:153)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: Obfuscation failed (result=1)
    at com.github.wvengen.maven.proguard.ProGuardMojo.proguardMain(ProGuardMojo.java:675)
    at com.github.wvengen.maven.proguard.ProGuardMojo.execute(ProGuardMojo.java:527)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Thanks,
Sharat Z

**Comment by FibreFoX** [comment]
Could you try to create a ["Minimal, Complete, and Verifiable example"](http://stackoverflow.com/help/mcve)?! As this project is not activly maintained, it is very hard to have some debugging examples.

**Comment by nchidipo** [comment]
I tried with simple project, there it got success. but it's failing with my development project.

Can we have webex session, So that i will show the complete information.

Please let me know, so that i will send you webex session link.

Thanks,
Sharat Z

**Comment by FibreFoX** [comment]
@nchidipo so this means you can't recreate that issue, neither making it point to the proguard-maven-plugin. Why are you thinking this is a bug of this maven-plugin? It might be your setup itself and not the proguard-maven-plugin.

As for the webex session: I'm not that experienced with proguard myself, just fooled around when integrating this maven-plugin with the javafx-maven-plugin and wanted to help here a bit ;)

**Comment by lx5210** [comment]
这个怎么解决的？我也遇到了这个问题
