### ISSUE TITLE
Proguard should not compress nested jars for spring boot applications

### ISSUE THREAD

**Issue by Amithpn** [wvengen/proguard-maven-plugin#54]
Not be able to run the proguard generated jar.
Proguard compresses the jar nested jar files due to which spring boot applications wont run properly with obfucated jar.

**Comment by Amithpn** [comment]
My Proguard conf file:

-dontobfuscate
-dontshrink
-dontoptimize
-dontnot
-dontwarn
-allowaccessmodification
-dontpreverify
-keepparameternames
-keepdirectories **
-keep public class * { public protected *;}
-keep class com.test.app.datacollection.** { public protected *;}
-keepattributes Exceptions,InnerClasses,Signature,Deprecated,SourceFile,LineNumberTable,*Annotation*,EnclosingMethod,LocalVariable*Table
-keepattributes Column
-keepattributes Table
-adaptresourcefilecontents **.properties,META-INF/MANIFEST.MF,META-INF/spring.*
-printmapping '${project.build.directory}/${project.artifactId}.log'

-keep class * extends *
-keep interface * extends *

-keepclassmembers class * {
							@org.springframework.beans.factory.annotation.Autowired *;
							@org.springframework.beans.factory.annotation.Value *;
							@org.springframework.context.annotation.Bean *;
							@org.springframework.beans.factory.annotation.Qualifier *;
							@org.springframework.stereotype.Repository *;
							@org.springframework.data.repository.NoRepositoryBean *;
						  }
-keep interface RegistrationRequestRepository { <methods>; }		
-keep public class org.springframework.**

-keep public class * { public private *; }
-keep interface com.test.app.datacollection.**{*;}

Maven Progurad Plugin:

<plugin>
				<groupId>com.github.wvengen</groupId>
				<artifactId>proguard-maven-plugin</artifactId>
				<dependencies>
					<dependency>
						<groupId>net.sf.proguard</groupId>
						<artifactId>proguard-base</artifactId>
						<version>5.2.1</version>
						<scope>runtime</scope>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>proguard</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<obfuscate>true</obfuscate>
					<includeDependency>false</includeDependency>
					<injar>${project.build.finalName}.jar</injar>
					
					<outjar>${project.build.finalName}-obfuscated.jar</outjar>
					
					<proguardInclude>${basedir}/proguard.conf</proguardInclude>
					<libs>
						<lib>${java.home}/lib/rt.jar</lib>
						<lib>${java.home}/lib/jce.jar</lib>
					</libs>
				</configuration>
			</plugin>

Exception:

Exception in thread "main" java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/javax.transaction-api-1.2.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:285)
at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:260)
at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:248)
at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:237)
at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)
at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(JarFileArchive.java:87)
at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(ExecutableArchiveLauncher.java:72)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:49)
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58)

**Comment by FibreFoX** [comment]
This is some duplicate: https://github.com/wvengen/proguard-maven-plugin/issues/48

1. you must provide some example-project, at best some ["mcve"](http://stackoverflow.com/help/mcve)
2. this plugin is some wrapper for using proguard via maven, therefor this maven-plugin might not be real source of your problem

**Comment by Amithpn** [comment]
I will attach the example-project in some time. Thanks in advance.

**Comment by FibreFoX** [comment]
@Amithpn any progress with your example project?

**Comment by FibreFoX** [comment]
last ping @Amithpn
